// Sector list + sector→qualification cascade, ported verbatim from form.html.

export interface SectorOption {
  value: string;
  label: string;
}

/** NTTC sectors (Section 12). value = key into QUALIFICATIONS, label = display text. */
export const SECTORS: SectorOption[] = [
  { value: "agriculture", label: "Agriculture, Forestry, and Fishery" },
  { value: "automotive_and_land_transport", label: "Automotive and Land Transportation" },
  { value: "construction", label: "Construction" },
  { value: "electrical_and_electronics", label: "Electrical and Electronics" },
  { value: "furniture", label: "Furniture and Fixtures" },
  { value: "garments", label: "Garments and Textiles" },
  {
    value: "heating_ventilation_airconditioning_and_refrigeration",
    label: "Heating, Ventilation, Airconditioning and Refrigeration",
  },
  { value: "health", label: "Human Health / Health Care" },
  {
    value: "information_and_communication_technology",
    label: "Information and Communication Technology",
  },
  { value: "maritime", label: "Maritime" },
  { value: "metals_and_engineering", label: "Metals and Engineering" },
  { value: "processed_food_and_beverages", label: "Processed Food & Beverages" },
  {
    value: "social_community_development_and_other_services",
    label: "Social, Community Development and Other Services",
  },
  { value: "tourism", label: "Tourism (Hotel and Restaurant)" },
  { value: "utilities", label: "Utilities" },
  { value: "visual_arts", label: "Visual Arts" },
  { value: "wholesale_and_retail_trading", label: "Wholesale and Retail Trading" },
];

/** Qualifications keyed by sector value. */
export const QUALIFICATIONS: Record<string, string[]> = {
  agriculture: [
    "Agricultural Crops Production NC II",
    "Agricultural Crops Production NC III",
    "Agroentrepreneurship NC II",
    "Agroentrepreneurship NC III",
    "Agroentrepreneurship NC IV",
    "Animal Health Care and Management NC III",
    "Animal Production (Poultry-Chicken) NC II",
    "Animal Production (Ruminants) NC II",
    "Animal Production (Swine) NC II",
    "Aquaculture NC II",
    "Artificial Insemination (Large Ruminants)",
    "Artificial Insemination (Swine) NC II",
    "Bamboo Production NC II",
    "Drying and Milling Plant Servicing NC III",
    "Fish Capture NC II",
    "Fishing Gear Repair and Maintenance NC III",
    "Grains Production NC II",
    "Horticulture NC III",
    "Landscape Installation and Maintenance",
    "Milking Operation NC II",
    "Organic Agriculture Production NC II",
    "Pest Management (Vegetables) NC II",
    "Rice Machinery Operations NC II",
    "Rubber Processing NC II",
    "Rubber Production NC II",
    "Seaweed Production NC II",
    "Coffee Production Level II",
    "Mango Production Level II",
  ],
  automotive_and_land_transport: [
    "Automotive Body Painting/Finishing NC III",
    "Automotive Body Repairing NC II",
    "Automotive Electrical Assembly NC II",
    "Automotive Electrical Assembly NC III",
    "Automotive Mechanical Assembly NC II",
    "Automotive Mechanical Assembly NC III",
    "Automotive Servicing NC II",
    "Automotive Servicing NC III",
    "Automotive Servicing NC IV",
    "Automotive Wiring Harness Assembly NC II",
    "Driving (Articulated Vehicle) NC III",
    "Driving (Passenger Bus/Straight Truck) NC III",
    "Driving NC II",
    "Painting Machine Operation NC II",
    "Plastic Machine Operation NC II",
    "Tinsmithing (Automotive Manufacturing) NC III",
    "Automotive Painting NC II",
    "Automotive Servicing (Chassis Repair) NC II",
    "Automotive Servicing (Electrical Repair) NC II",
  ],
  construction: [
    "Carpentry NC II",
    "Carpentry NC III",
    "Construction Painting NC II",
    "Construction Painting NC III",
    "Heavy Equipment Operation (Articulated Off-Heavy Equipment Operation (Backhoe Loader) NC II",
    "Heavy Equipment Operation (Bulldozer) NC II",
    "Heavy Equipment Operation (Concrete Pump) NC",
    "Heavy Equipment Operation (Container Stacker) NC II",
    "Heavy Equipment Operation (Forklift) NC II",
    "Heavy Equipment Operation (Gantry Crane) NC II",
    "Heavy Equipment Operation (Hydraulic) NC II",
    "Heavy Equipment Operation (Motor Grader) NC II",
    "Heavy Equipment Operation (Paver) NC II",
    "Heavy Equipment Operation (Rigid Off-Highway Dump) NC II",
    "Heavy Equipment Operation (Rigid On-Highway Dump) NC II",
    "Heavy Equipment Servicing (Mechanical) NC II",
    "Masonry NC II",
    "Masonry NC III",
    "Pipfitting (Metallic) NC II",
    "Pipfitting NC II",
    "Plumbing NC II",
    "PV System Design NC III",
    "PV Systems Installation NC II",
    "PV Systems Servicing NC III",
    "Rigging NC I",
    "Scaffold Erection NC II",
    "Scaffolding Works NC II (Supported Type Scaffold)",
    "Technical Drafting NC II",
    "Tile Setting NC II",
    "Construction Site Supervision Level IV",
  ],
  electrical_and_electronics: [
    "Computer Systems Servicing NC II",
    "Consumer Electronics Servicing NC III",
    "Consumer Electronics Servicing NC IV",
    "Electrical Installation and Maintenance NC II",
    "Electrical Installation and Maintenance NC III",
    "Electrical Installation and Maintenance NC IV",
    "Electronic Products Assembly and Servicing NC II",
    "Instrumentation and Control Servicing NC II",
    "Instrumentation and Control Servicing NC III",
    "Instrumentation and Control Servicing NC IV",
    "Mechatronics Servicing NC II",
    "Mechatronics Servicing NC III",
    "Semiconductor Back-End Operation NC II",
    "Semiconductor Front-of-Line Operation NC II",
    "Production Line - Back End Operation Electronics",
    "Production Line - SMT Operation Level",
  ],
  furniture: ["Furniture Making (Finishing) NC II"],
  garments: [
    "Dressmaking NC II",
    "Fashion Design (Apparel) NC III",
    "Tailoring NC II",
    "Industrial Sewing Machine Operation",
  ],
  heating_ventilation_airconditioning_and_refrigeration: [
    "Air Duct Servicing NC II",
    "Ice Plant Refrigeration Servicing NC III",
    "RAC Servicing (DOMRAC) NC II",
    "RAC Servicing (PACU-CR) NC III",
    "Transport RAC Servicing NC II",
  ],
  health: [
    "Barangay Health Services NC II",
    "Biomedical Equipment Services NC II",
    "Caregiving (Clients with Special Needs) NC II",
    "Caregiving (Elderly) NC II",
    "Caregiving (Grade Schooler to Adolescent) NC II",
    "Caregiving (Newborn to Preschooler) NC II",
    "Caregiving NC II",
    "Dental Hygiene Level IV",
    "Dental Laboratory Technology Services (Fixed Dental Laboratory Technology)",
    "Dental Technology NC IV",
    "Emergency Medical Services NC II",
    "Health Care Services NC II",
    "Hilot (Wellness Massage) NC II",
    "Massage Therapy NC II",
    "Ophthalmic Lens Services NC II",
    "Pharmacy Services NC III",
    "Barangay Infectious Disease Management",
    "Contact Tracing Level II",
  ],
  information_and_communication_technology: [
    "2D Animation NC III",
    "2D Game Art Development NC III",
    "3D Animation NC III",
    "3D Game Art Development NC III",
    "Animation NC II",
    "Broadband Installation (Fixed Wireless Systems)",
    "Cable TV Installation NC II",
    "Cable TV Operation and Maintenance NC III",
    "Contact Center Services NC II",
    "Game Programming NC III",
    "Medical Transcription NC II",
    "Programming (.NET Technology) NC III",
    "Programming (Java) NC II",
    "Programming (Java) NC III",
    "Programming (Oracle Database) NC III",
    "Telecom OSP and Subscriber Line Installation",
    "Telecom OSP Installation (Fiber Optic Cable) NC II",
    "Visual Graphic Design NC II",
    "Visual Graphic Design NC III",
    "Web Development NC III",
    "Computer Security Incident Handling Level I",
    "Creative Web Design",
    "Web Development",
  ],
  maritime: ["Ship's Catering Services NC I", "Ships' Catering NC III (Ships' Cooks)"],
  metals_and_engineering: [
    "CAD/CAM Operation NC III",
    "CNC Lathe Machine Operation NC II",
    "CNC Lathe Machine Operation NC III",
    "CNC Milling Machine Operation NC II",
    "CNC Milling Machine Operation NC III",
    "Flux-Cored Arc Welding (FCAW) NC II",
    "Flux-Cored Arc Welding (FCAW) NC III",
    "Gas Metal Arc Welding (GMAW) NC II",
    "Gas Metal Arc Welding (GMAW) NC III",
    "Gas Tungsten Arc Welding (GTAW) NC II",
    "Gas Tungsten Arc Welding (GTAW) NC IV",
    "Gas Welding NC II",
    "Machining NC II",
    "Machining NC III",
    "Shielded Metal Arc Welding (SMAW) NC II",
    "Shielded Metal Arc Welding (SMAW) NC III",
    "Shielded Metal Arc Welding (SMAW) NC IV",
    "Submerged Arc Welding (SAW) NC II",
    "Tool and Die Making NC II",
  ],
  processed_food_and_beverages: [
    "Fish Products Packaging NC II",
    "Food Processing NC II",
    "Food Processing NC III",
    "Food Processing NC IV",
    "Slaughtering Operations (Large Animal) NC II",
    "Slaughtering Operations (Swine) NC II",
  ],
  social_community_development_and_other_services: [
    "Barbering NC II",
    "Beauty Care (Nail Care) Services NC II",
    "Beauty Care (Skin Care) Services NC II",
    "Beauty Care NC II",
    "Beauty Care Services (Nail Care) NC II",
    "Bookkeeping NC III",
    "Domestic Work NC II - Without Electives",
    "Domestic Work NC II",
    "Early Childhood Care and Development Services NC III",
    "Hairdressing NC II",
    "Hairdressing NC III",
    "Lifeguard Services NC II",
    "Lifeguard Services NC III",
    "Microfinance Technology NC II",
    "Real Estate Services NC II",
    "Security Services NC II",
    "Cooperative Development and Management Level I",
  ],
  tourism: [
    "Barista NC II",
    "Bartending NC II",
    "Bread and Pastry Production NC II",
    "Commercial Cooking NC II",
    "Commercial Cooking NC IV",
    "Cookery NC II",
    "Events Management Services NC III",
    "Food and Beverage Services NC II",
    "Food and Beverage Services NC III",
    "Food and Beverage Services NC IV",
    "Front Office Services NC II",
    "Housekeeping NC II",
    "Housekeeping NC III",
    "Housekeeping NC IV",
    "Local Guiding Services NC II",
    "Tourism Promotion Services NC II",
    "Travel Services NC II",
  ],
  utilities: [
    "Line Construction (Electric Power Distribution) NC II",
    "Transmission Line Installation and Maintenance NC II",
    "Transmission Line Installation and Maintenance NC III",
  ],
  visual_arts: ["Illustration NC II", "Photography NC II"],
  wholesale_and_retail_trading: ["Customer Services NC II"],
};

/** Display label for a sector value. */
export function sectorLabel(value: string): string {
  return SECTORS.find((s) => s.value === value)?.label ?? value;
}
